
								-- TELECOM CUSTOMER CHURN PROJECT
								-- FILE: 03_Business_Insights.sql
								-- PURPOSE:
								-- Business Insights + Churn Risk Analysis



-- =========================================================
-- SECTION 1 — CHURN RISK ANALYSIS
-- =========================================================



-- Q1 Show churn percentage by contract type

SELECT Contract,

(
    COUNT(
        CASE
            WHEN Churn = 'Yes' THEN 1
        END
    ) * 100.0 / COUNT(*)

) AS churn_percentage

FROM telecom_customer

GROUP BY Contract;



-- Q2 Show churn percentage by payment method

SELECT PaymentMethod,

(
    COUNT(
        CASE
            WHEN Churn = 'Yes' THEN 1
        END
    ) * 100.0 / COUNT(*)

) AS churn_percentage

FROM telecom_customer

GROUP BY PaymentMethod;



-- Q3 Show churn percentage by internet service

SELECT InternetService,

(
    COUNT(
        CASE
            WHEN Churn = 'Yes' THEN 1
        END
    ) * 100.0 / COUNT(*)

) AS churn_percentage

FROM telecom_customer

GROUP BY InternetService;



-- Q4 Show churn percentage among senior citizens vs non-senior citizens

SELECT

    CASE
        WHEN SeniorCitizen = 1 THEN 'Senior Citizen'
        ELSE 'Non-Senior Citizen'
    END AS customer_type,

(
    COUNT(
        CASE
            WHEN Churn = 'Yes' THEN 1
        END
    ) * 100.0 / COUNT(*)

) AS churn_percentage

FROM telecom_customer

GROUP BY SeniorCitizen;





-- =========================================================
-- SECTION 2 — REVENUE ANALYSIS
-- =========================================================



-- Q5 Show total revenue generated by churned customers

SELECT SUM(TotalCharges) AS total_revenue

FROM telecom_customer

WHERE Churn = 'Yes';



-- Q6 Show total revenue generated by non-churned customers

SELECT SUM(TotalCharges) AS total_revenue

FROM telecom_customer

WHERE Churn = 'No';



-- Q7 Show average revenue by contract type

SELECT Contract,
       AVG(TotalCharges) AS average_revenue

FROM telecom_customer

GROUP BY Contract;



-- Q8 Show top 5 contract-payment combinations generating highest revenue

SELECT Contract,
       PaymentMethod,
       SUM(TotalCharges) AS highest_revenue

FROM telecom_customer

GROUP BY Contract, PaymentMethod

ORDER BY highest_revenue DESC

LIMIT 5;





-- =========================================================
-- SECTION 3 — CUSTOMER RETENTION ANALYSIS
-- =========================================================



-- Q9 Show average tenure of churned customers

SELECT AVG(tenure) AS avg_tenure_churned

FROM telecom_customer

WHERE Churn = 'Yes';



-- Q10 Show average tenure of non-churned customers

SELECT AVG(tenure) AS avg_tenure_non_churned

FROM telecom_customer

WHERE Churn = 'No';



-- Q11 Show customers with high monthly charges but low tenure

SELECT customerID,
       MonthlyCharges,
       tenure

FROM telecom_customer

ORDER BY MonthlyCharges DESC,
         tenure ASC;





-- =========================================================
-- SECTION 4 — CUSTOMER SEGMENTATION
-- =========================================================



-- Q12 Show customer count by Contract and Churn

SELECT Contract,
       Churn,
       COUNT(*) AS customer_count

FROM telecom_customer

GROUP BY Contract, Churn;



-- Q13 Show customer count by InternetService and Churn

SELECT InternetService,
       Churn,
       COUNT(*) AS customer_count

FROM telecom_customer

GROUP BY InternetService, Churn;



-- Q14 Show customer count by PaymentMethod and Churn

SELECT PaymentMethod,
       Churn,
       COUNT(*) AS customer_count

FROM telecom_customer

GROUP BY PaymentMethod, Churn;





-- =========================================================
-- SECTION 5 — ADVANCED ANALYST THINKING
-- =========================================================



-- Q15 Contract type with highest customers, churn and revenue

SELECT Contract,

       COUNT(*) AS total_customers,

       COUNT(
           CASE
               WHEN Churn = 'Yes' THEN 1
           END
       ) AS churn_customers,

       SUM(TotalCharges) AS total_revenue

FROM telecom_customer

GROUP BY Contract

ORDER BY total_customers DESC;



-- Q16 Most risky payment method based on churn customers

SELECT PaymentMethod,

       COUNT(
           CASE
               WHEN Churn = 'Yes' THEN 1
           END
       ) AS churn_customers

FROM telecom_customer

GROUP BY PaymentMethod

ORDER BY churn_customers DESC;



-- Q17 Customer segments for retention campaigns

SELECT

    CASE
        WHEN tenure < 12 THEN 'Low Tenure'
        WHEN tenure BETWEEN 12 AND 36 THEN 'Medium Tenure'
        ELSE 'High Tenure'
    END AS tenure_group,

    CASE
        WHEN MonthlyCharges < 50 THEN 'Low Charges'
        ELSE 'High Charges'
    END AS charges_group,

    COUNT(
        CASE
            WHEN Churn = 'Yes' THEN 1
        END
    ) AS churn_customers

FROM telecom_customer

GROUP BY tenure_group, charges_group

ORDER BY churn_customers DESC;